const time=document.getElementById('time');let greeting=document.getElementById('greeting');let h2=document.querySelector(".h2");let name=document.getElementById('name');let focus=document.getElementById('focus');const amPmButton=document.getElementById('1');const militaryTimeButton=document.getElementById('2');const morningImages=['https://i.ibb.co/7vDLJFb/morning.jpg','images/morning1.jpg','images/morning2.jpg','images/morning3.jpg','images/morning4.jpg','images/morning5.jpg'];const morningImgRandom=morningImages[Math.floor(Math.random()*6)];const afternoonImages=['https://i.ibb.co/3mThcXc/afternoon.jpg','images/evening1.jpg','images/evening2.jpg','images/evening3.jpg','images/evening4.jpg','images/evening5.jpg'];const afternoonImgRandom=afternoonImages[Math.floor(Math.random()*6)];const nightImages=['https://i.ibb.co/924T2Wv/night.jpg','images/night1.jpg','images/night2.jpg','images/night3.jpg','images/night4.jpg','images/night5.jpg'];const nightImgRandom=nightImages[Math.floor(Math.random()*6)];focus.classList.add('type');focus.addEventListener("animationend",function(){focus.style.borderRight='none'})
showAmPm=!0;showMilitaryTime=!1;amPmButton.addEventListener('click',function(){if(showAmPm==!0)showAmPm=!1;else showAmPm=!0;if(amPmButton.textContent=="Remove Am/Pm")amPmButton.textContent="Add Am/Pm";else amPmButton.textContent="Remove Am/Pm"});militaryTimeButton.addEventListener('click',function(){if(showMilitaryTime==!1)showMilitaryTime=!0;else showMilitaryTime=!1});function showTime(){let currentTime=new Date(),hour=currentTime.getHours(),min=currentTime.getMinutes(),sec=currentTime.getSeconds(),militaryHour=currentTime.getHours();const amPm=hour>=12?'PM':'AM';hour=hour%12||12;if(showMilitaryTime==!1){time.innerHTML=`${hour}<span>:</span>${addZero(min)}<span>:</span>${addZero(sec)} ${showAmPm ? amPm : ''}`}else{time.innerHTML=`${militaryHour}<span>:</span>${addZero(min)}<span>:</span>${addZero(sec)} ${showAmPm ? amPm : ''}`}
setTimeout(showTime,1000)}
function addZero(n){return(parseInt(n,10)<10?'0':'')+n}
function setBgGreet(){let currentTime=new Date(),hour=currentTime.getHours(),militaryHour=currentTime.getHours();if(hour<12||militaryHour<12){if(morningImgRandom==`images/morning3.jpg`){h2.style.opacity='1'}else if(morningImgRandom==`images/morning4.jpg`){h2.style.opacity='.8'}
document.body.style.backgroundImage=`url(${morningImgRandom})`;document.body.style.backgroundSize="cover";greeting.textContent='Good Morning'}else if(hour<20||militaryHour<20){if(afternoonImgRandom==`images/evening5.jpg`){time.style.color='white';greeting.style.color='white';name.style.color='white';h2.style.color='white';h2.style.opacity='.8'}
document.body.style.backgroundImage=`url(${afternoonImgRandom})`;document.body.style.backgroundSize="cover";greeting.textContent='Good Afternoon'}else{document.body.style.backgroundImage=`url(${nightImgRandom})`;document.body.style.backgroundSize="cover";greeting.textContent='Good Evening';document.body.style.color='white'}}
function getName(){if(localStorage.getItem('name')==''){localStorage.clear()}else{name.value=localStorage.getItem('name')}}
function setName(e){if(e.type==='keypress'){if(e.keyCode==13){localStorage.setItem('name',name.value);name.blur()}}else{localStorage.setItem('name',name.value)}}
function getFocus(){if(localStorage.getItem('focus')==''){localStorage.clear()}else{focus.value=localStorage.getItem('focus');focus.classList.remove('type')}}
function setFocus(e){if(e.type==='keypress'){if(e.keyCode==13){localStorage.setItem('focus',focus.value);focus.blur()}}else{localStorage.setItem('focus',focus.value)}}
name.addEventListener('keypress',setName);name.addEventListener('blur',setName);focus.addEventListener('keypress',setFocus);focus.addEventListener('blur',setFocus);showTime();setBgGreet();getName();getFocus()